---
title: "Lab 7 Rank Based Test"
author: "Angie Bouche"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi it's Angie. I created a new lab.

Collaborators!!!!!!!!
I'm going to make some histogram s

```{r}
library(tidyverse)

kermit <- read_csv("kermit.csv")

kermit_hist <- ggplot(kermit, aes(x=Score.pre)) +
  geom_histogram() +
  facet_wrap(~Gender)

kermit_hist
```

Back to the creater
I'm doing to do some rank based tests

```{r}

#Is there a significant difference in pre-talk Kermit scores for males and females?

#Unpaired data, so we will use Mann-Whitney U

mwu_kermit <- kermit %>% 
  wilcox.test(Score.pre ~ Gender, data = .)

```

There is not a difference in ranks between females and males. 



Is there a significant difference in Kermit ranks for pre-talk and post-talk (ignoring all other variables)

Null: NO

```{r}
wsr_kermit <- wilcox.test(kermit$Score.pre, kermit$Score.post, paired = TRUE)

wsr_kermit

#there is no significant difference in kermit rankings before and after his talk (summary....)
```

